### ISSUE TITLE
Suicide vest script for fedayen that allows them to detonate on command

### ISSUE THREAD

**Issue by Totyano** [Totyano/Eternal-Babylon-TVT#4]

**Comment by tanaaKa** [comment]
Ooooooo. I'll take this one.

**Comment by tanaaKa** [comment]
Adding here for later:

Use "take" event handler to check for vest classname, if so, add ace suicide bomb action

[this](https://community.bistudio.com/wiki/Magic_Variables#this_2) [addEventHandler](https://community.bistudio.com/wiki/addEventHandler) ["Take", {
	[params](https://community.bistudio.com/wiki/params) ["_unit", "_container", "_item"];
	
	if (typeOf _item isNotEqualTo "suicidevestclassname") exitWith {};
	
	// Add ace action
}];

**Comment by tanaaKa** [comment]
Completed in https://github.com/Totyano/Eternal-Babylon-TVT/pull/6
